### ISSUE TITLE
Registration on BEV

### ISSUE THREAD

**Issue by Snow-know-nothing** [zjuluolun/BEVPlace#10]
Thank you for your work! I am wondering if I can use the local features output by the group convolutional network for registration between BEV images to get 2D pose?

**Comment by zjuluolun** [comment]
Thanks for your interest. Yes, registration on BEV can produce accurate 2D poses. I'm preparing a journal extension of BEVPlace, which has included this idea. It seems that we are on the same page hh!

**Comment by Snow-know-nothing** [comment]
Wow，hope to see it soon！

**Comment by manujnaman** [comment]
BEVPlace++ paper looks very interesting. Are you all planning to post your current checkpoint?

**Comment by zjuluolun** [comment]
Hi @manujnaman,

I uploaded a checkpoint that you can evaluate now.

**Comment by zjuluolun** [comment]
Hi @Snow-know-nothing,

Our new version, BEVPlace++, has been released. Looking forward to more discussions!

**Comment by ZhangZh3ng** [comment]
> Hi @manujnaman,
> 
> I uploaded a checkpoint that you can evaluate now.

Hello, I can't find the checkpoint file that your mentioned, can you point out where it is? (The run/Aug08_11-51-06 contians no checkpoint file)

**Comment by ZhangZh3ng** [comment]
> Hi @manujnaman,
> 
> I uploaded a checkpoint that you can evaluate now.

@zjuluolun Hello, I couldn't locate the checkpoint file you mentioned. Could you please clarify where it is? I assume it might be in the run/Aug08_11-51-06 directory, but I wasn't able to find any checkpoint file there.

**Comment by zjuluolun** [comment]
> > Hi @manujnaman,
> > I uploaded a checkpoint that you can evaluate now.
> 
> @zjuluolun Hello, I couldn't locate the checkpoint file you mentioned. Could you please clarify where it is? I assume it might be in the run/Aug08_11-51-06 directory, but I wasn't able to find any checkpoint file there.

@ZhangZh3ng Thanks for figuring out the issue. I uploaded a new checkpoint, which is located in the directory "run/Aug08_11-51-06"
