### ISSUE TITLE
I  got a problem

### ISSUE THREAD

**Issue by goldtimes** [zjuluolun/BEVPlace#17]
(torch2.0) ➜  BEVPlace python3 main.py --mode=test --load_from=./runs/Nov22_09-10-15 --ckpt='latest'

===> Building model
/home/kilox/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/kilox/anaconda3/envs/torch2.0/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet34_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet34_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
=> loading checkpoint './runs/Nov22_09-10-15/checkpoint.pth.tar'
=> loaded checkpoint './runs/Nov22_09-10-15/checkpoint.pth.tar' (epoch 39)
===> Running evaluation step
====> Extracting Features of KITTI and calculating recalls
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 204/204 [00:09<00:00, 22.59it/s]
Traceback (most recent call last):
  File "main.py", line 376, in <module>
    recall_top1, success_rate, mean_trans_err, mean_rot_err = kitti_dataset.evaluateResults(seq, global_descs, local_feats, test_set, "out_imgs/")
  File "/home/kilox/hang_ws/BEVPlace/kitti_dataset.py", line 156, in evaluateResults
    recall_top1 = tp / all_positives #tp/(tp+fp)
ZeroDivisionError: division by zero

**Comment by zjuluolun** [comment]
Hi, I just fixed some bugs for visualization. You can pull the latest codes and try it again.

**Comment by goldtimes** [comment]
I updated the latest code, and the kitty dataset is no longer reporting errors.
