### ISSUE TITLE
Request for training scripts 

### ISSUE THREAD

**Issue by heroacool** [zjuluolun/BEVPlace#2]
@zjuluolun Hello,  I am exploring the BEVPlace project and find it very useful. 
However, I noticed that the training scripts for the models are not provided in the repository. Would it be possible for you to share the training scripts used to train the models? This would be very helpful for me and other users who are interested in experimenting with the models. Thank you in advance for your time and consideration.

**Comment by zjuluolun** [comment]
Thanks for your interest. The training scripts are not released at this stage since our paper is still under peer review. You could use our pre-trained model for evaluation if you want to compare BEVPlace with your method.

**Comment by xy1999729** [comment]
> Thanks for your interest. The training scripts are not released at this stage since our paper is still under peer review. You could use our pre-trained model for evaluation if you want to compare BEVPlace with your method.

Congratulations! I recently heard that your paper was accepted by ICCV and I am really interested in your work,  so could you please release your training script recently?

**Comment by RaphaelLorenzo** [comment]
Hi thanks for sharing your work and the pretrained models, do you have any plans yet to release the training scripts ?

**Comment by whu-lyh** [comment]
Any schedule?

**Comment by ZhouZijie77** [comment]
Hello, any plans to share your training scripts recently?

**Comment by ANXPAX** [comment]
Hello, Team congratulations for your SOTA work . Please share your training scripts with us.

**Comment by manujnaman** [comment]
If possible, please give pointers to how training can be done on a custom dataset. Thank you.

**Comment by zjuluolun** [comment]
Hi, a stronger method BEVPlace++ has been released with its training scripts.
