### ISSUE TITLE
Ground Truth of Loop closure detection 

### ISSUE THREAD

**Issue by ydragon719** [zjuluolun/BEVPlace#3]
How do you get the ground truth of the loop. I'm interested in your work, in the process of reproduction, how do you get the ground truth of loops in datasets such as kitti? The number of true loops and the position of the two frames corresponding to the loop are important for the calculation of evaluation indicators such as accuracy and recall. Can you provide your method or code?

**Comment by zjuluolun** [comment]
Thanks for your interest. We regard two frames as loop frames if their ground truth distance is less than a threshold. This threshold is set to 5 meters for KITTI and 25 meters for the benchmark dataset. The dataset partition of KITTI has been implemented in the dataset.py script. More details of our experiments can be found in our preprint paper.
