### ISSUE TITLE
Wrong calculation of  "Mean AR@1" and "Mean AR@1%" in Tab.5

### ISSUE THREAD

**Issue by sijieaaa** [zjuluolun/BEVPlace#4]
Hi Lunluo,

It seems the calculation of "Mean AR@1" and "Mean AR@1%" in Tab.5 is not correct.

(96.5 + 96.9 + 92.3 +95.3)/4 = 95.25
(99.0 + 99.7 + 98.7 + 99.5)/4 = 99.225

Thanks for your attention.

**Comment by zjuluolun** [comment]
Thanks! We'll correct this number in our revision paper.
