### ISSUE TITLE
SLAM Application

### ISSUE THREAD

**Issue by robertsenputras** [zjuluolun/BEVPlace#5]
Hi zjuluolun,

Thanks for the code of your precious BEVPlace. I saw some application that can be done using this algorithm, such as Place Recognition, Loop closing detection, and pose estimator. 

In terms of Place Recognition and Loop Closing detection this algorithm needs previous global map database, right? However, I'm curious about SLAM. If we don't have a map database yet, how can we apply this code to a SLAM (Mapping) problem?

Thank you

**Comment by zjuluolun** [comment]
Thanks for your interest. For SLAM, loop usually appears when the robot drives for some distance. In this case,  we build the map database using the previously seen data scans. Based on such a database, our method can detect loop closures to reduce drift.
