### ISSUE TITLE
The KITTI dataset in the Table 1

### ISSUE THREAD

**Issue by FudongGe** [zjuluolun/BEVPlace#6]
Hi Lunluo,

It seems that the number of the KITTI dataset in the Table 1 is different from the raw dataset downloaded from the official website. For example, there are 4541 bin files from 0000 to 4500 for the sequence 00. But in the Table 1, you mention that it's 0-3000 for the database, and 3200-4650 for the query. Have you made any changes to the dataset？

Thanks for your attention.

**Comment by zjuluolun** [comment]
Thanks for your interest. We ignore some scans for each sequence of KITTI to make sure that the query scans and the database scans are well departed.

**Comment by FudongGe** [comment]
> Thanks for your interest. We ignore some scans for each sequence of KITTI to make sure that the query scans and the database scans are well departed.

Dear Lun,

I understand, but there are only 4541 bin files for the sequence 00. And in the Table 1, you mention that it's 3200-4650 for the query. Where is the '4541-4650'? Maybe you wrote something wrong?

**Comment by zjuluolun** [comment]
Hello @FudongGe ,
   It is actually a typo. The correct query frames are  3200-4541 as wrote in the dataset.py.

**Comment by FudongGe** [comment]
> Hello @FudongGe , It is actually a typo. The correct query frames are 3200-4541 as wrote in the dataset.py.

Dear Lun.

Thanks, and I know now. Looking forward to your training scripts! 

I will close this issue.
